# Form implementation generated from reading ui file 'designer\mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("designer\\../icons/mainwindow_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.search_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.search_label.setGeometry(QtCore.QRect(217, 10, 211, 16))
        self.search_label.setObjectName("search_label")
        self.search_box = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.search_box.setGeometry(QtCore.QRect(210, 30, 341, 41))
        self.search_box.setObjectName("search_box")
        self.result_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(10, 440, 771, 151))
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")
        self.ptbr_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.ptbr_button.setGeometry(QtCore.QRect(668, 30, 111, 20))
        self.ptbr_button.setObjectName("ptbr_button")
        self.en_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.en_button.setGeometry(QtCore.QRect(668, 60, 111, 20))
        self.en_button.setObjectName("en_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Keki"))
        self.search_label.setText(_translate("MainWindow", "What manga do you wanna read?"))
        self.ptbr_button.setText(_translate("MainWindow", "portuguese"))
        self.en_button.setText(_translate("MainWindow", "english"))
