# Form implementation generated from reading ui file 'designer\reading_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Keki:reading(object):
    def setupUi(self, Keki:reading):
        Keki:reading.setObjectName("Keki:reading")
        Keki:reading.resize(587, 859)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("designer\\../icons/mainwindow_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Keki:reading.setWindowIcon(icon)
        self.pushButton = QtWidgets.QPushButton(parent=Keki:reading)
        self.pushButton.setGeometry(QtCore.QRect(190, 830, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Keki:reading)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 830, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Keki:reading)
        QtCore.QMetaObject.connectSlotsByName(Keki:reading)

    def retranslateUi(self, Keki:reading):
        _translate = QtCore.QCoreApplication.translate
        Keki:reading.setWindowTitle(_translate("Keki:reading", "Dialog"))
        self.pushButton.setText(_translate("Keki:reading", "<"))
        self.pushButton_2.setText(_translate("Keki:reading", ">"))
